

services:
  postgres:
    image: postgres
    container_name: my_postgres
    environment: 
      POSTGRES_PASSWORD: postgres
    volumes:
      - .pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"
  redis:
    image: redis
    container_name: my_redis
    ports: 
     - "6379:6379"
    restart: unless-stopped
    volumes:
      - .rddata:/data
    command: redis-server --appendonly yes
      
volumes:
  .pgdata:
  .rddata:
    driver: local
